// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtSUxnn-L_fqaZ37fGTIOjO1EvqQn39LM',
    appId: '1:206910421921:web:249b767b20c4f4f6d869e0',
    messagingSenderId: '206910421921',
    projectId: 'dakachatgptv2',
    authDomain: 'dakachatgptv2.firebaseapp.com',
    storageBucket: 'dakachatgptv2.appspot.com',
    measurementId: 'G-VX30Z6K2ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVJqYWwS4H9vcBotmTf9IM_DriGD39ccA',
    appId: '1:206910421921:android:9adf356d1a1b6c0fd869e0',
    messagingSenderId: '206910421921',
    projectId: 'dakachatgptv2',
    storageBucket: 'dakachatgptv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjoyQXCGad1E9ohjlieASIgJiMKm-IBQ',
    appId: '1:206910421921:ios:7ea05131b03523b0d869e0',
    messagingSenderId: '206910421921',
    projectId: 'dakachatgptv2',
    storageBucket: 'dakachatgptv2.appspot.com',
    iosBundleId: 'com.devsaci.dakachatgptV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvjoyQXCGad1E9ohjlieASIgJiMKm-IBQ',
    appId: '1:206910421921:ios:46b62c40b23c85ddd869e0',
    messagingSenderId: '206910421921',
    projectId: 'dakachatgptv2',
    storageBucket: 'dakachatgptv2.appspot.com',
    iosBundleId: 'com.devsaci.dakachatgptV2.RunnerTests',
  );
}
